name: momento_booth
description: Opensource photobooth application

publish_to: "none"
version: 0.5.3+71

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # i18n
  flutter_localizations:
    sdk: flutter
  intl: 0.18.1

  # UI
  auto_size_text: 3.0.0
  fluent_ui: 4.7.5
  go_router: 11.1.2
  flutter_svg: 2.0.7
  animated_text_kit: 4.2.2
  flutter_scroll_shadow: 1.2.3
  flutter_layout_grid: 2.0.5
  pretty_qr_code: 3.0.0
  confetti: 0.7.0
  wave: 0.2.2
  texture_rgba_renderer:
    git: https://github.com/h3x4d3c1m4l/flutter_texture_rgba_renderer

  # Printscreen/Image processing
  screenshot: 2.1.0
  image: 4.1.3

  # MVC
  mobx: 2.2.0
  flutter_mobx: 2.1.0

  # Models
  freezed_annotation: 2.4.1
  json_annotation: 4.8.1

  # Interop
  ffi: 2.1.0
  flutter_rust_bridge: 1.82.1

  # Printing
  printing: 5.11.0
  pdf: 3.10.4

  # System
  path_provider: 2.1.1
  path: 1.8.3
  window_manager: 0.3.6
  file_selector: 1.0.1

  # Log and error handling
  loggy: 2.0.3
  flutter_loggy: 2.0.2
  sentry_flutter: 7.10.1

  # Misc
  meta: 1.9.1
  toml: 0.14.0
  synchronized: 3.1.0
  collection: 1.17.2
  win32: 5.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  # MVC
  mobx_codegen: 2.4.0

  # Code quality
  flutter_lints: 2.0.3

  # Models
  freezed: 2.4.3
  json_serializable: 6.7.1

  # Code generation
  build_runner: 2.4.6
  ffigen: 8.0.2

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/bitmap/
    - assets/svg/
    - assets/fonts/brandon_grotesque/
    - assets/scripts/

  fonts:
    - family: Brandon Grotesque
      fonts:
        - asset: assets/fonts/brandon_grotesque/Brandon_light.otf
          weight: 300
          
