name: momento_booth
description: Opensource photobooth application

publish_to: "none"
version: 0.13.1+104

environment:
  sdk: ^3.6.0

dependencies:
  flutter: { sdk: flutter }

  # i18n
  flutter_localizations: { sdk: flutter }
  intl: any

  # UI
  auto_size_text: 3.0.0
  fluent_ui: 4.10.0
  go_router: 14.6.3
  flutter_svg: 2.0.17
  animated_text_kit: 4.2.2
  flutter_scroll_shadow: 1.2.4
  flutter_layout_grid: 2.0.7
  pretty_qr_code: 3.3.0
  confetti: 0.8.0
  wave: 0.2.2
  texture_rgba_renderer: { git: https://github.com/momentobooth/flutter_texture_rgba_renderer }
  lottie: 3.3.0
  smooth_scroll_multiplatform: 1.0.8
  widgetbook: 3.10.2
  widgetbook_annotation: 3.2.0
  flex_color_picker: 3.7.0
  lucide_icons_flutter: 1.2.5

  # Printscreen/Image processing
  screenshot: 3.0.0

  # MVC
  mobx: 2.5.0
  flutter_mobx: 2.3.0

  # Models
  freezed_annotation: 2.4.4
  json_annotation: 4.9.0

  # Rust library/Interop
  rust_lib_momento_booth: { path: rust_builder }
  ffi: 2.1.3
  flutter_rust_bridge: 2.7.0

  # Printing
  printing: 5.13.4
  pdf: 3.11.1

  # System
  path_provider: 2.1.5
  path: ^1.9.0
  window_manager: 0.4.3
  file_selector: 1.0.3
  win32: 5.10.0

  # Log and error handling
  talker: 4.6.2
  talker_flutter: 4.6.2
  sentry_flutter: 8.12.0

  # Sound output
  just_audio: 0.9.43
  just_audio_media_kit: 2.0.6
  media_kit_libs_linux: any
  media_kit_libs_windows_audio: any

  # Storage
  flutter_secure_storage: 9.2.4
  toml: 0.16.0

  # Networking
  http: 1.2.2
  http_parser: 4.1.2
  mqtt5_client: 4.5.3

  # Misc
  get_it: 8.0.3
  meta: any
  synchronized: 3.3.0+3
  collection: any
  dart_casing: 3.0.1
  package_info_plus: 8.1.2
  lemberfpsmonitor: 0.0.3+6
  crypto: 3.0.6
  draggable_scrollbar: 0.1.0
  csslib: 1.0.2

dev_dependencies:
  # UI
  widgetbook_generator: 3.9.1

  # MVC
  mobx_codegen: 2.7.0

  # Code quality
  flutter_lints: 5.0.0

  # Models
  freezed: 2.5.7
  json_serializable: 6.9.0

  # Code generation
  build_runner: 2.4.14

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/bitmap/
    - assets/svg/
    - assets/fonts/brandon_grotesque/
    - assets/scripts/
    - assets/sounds/

  fonts:
    - family: Brandon Grotesque
      fonts:
        - asset: assets/fonts/brandon_grotesque/Brandon_light.otf
          weight: 300
