[package]
name = "momento_booth_native_helpers"
version = "0.1.0"
edition = "2021"

[lib]
name = "momento_booth_native_helpers"
crate-type = ["lib", "staticlib", "cdylib"]

[dependencies]
derive_more = "0.99.17"
atom_table = "1.1.0"
flutter_rust_bridge = "1.80.1"
ffsend-api = "0.7.3"
serde_json = "1.0.103"
chrono = "0.4.26"
image = "0.24.6"
nokhwa = { git = "https://github.com/l1npengtul/nokhwa", branch="0.10", features = ["input-native", "output-threaded"] }
zune-jpeg = "0.3.17"
jpeg-encoder = "0.5.1"
static_init = "1.0.3"
lazy_static = "1.4.0"
dlopen = "0.1.8"
noise = "0.8.2"
dashmap = "5.5.0"
turborand = "0.10.0"
pathsep = "0.1.1"
tokio = "1.29.1"
gphoto2 = "3.2.1"

[profile.dev]
opt-level = 3
