[package]
name = "momento_booth_native_helpers"
version = "0.1.0"
edition = "2021"

[lib]
name = "momento_booth_native_helpers"
crate-type = ["lib", "staticlib", "cdylib"]

[dependencies]
anyhow = "1.0.81"
derive_more = "0.99.17"
atom_table = "1.1.0"
flutter_rust_bridge = "=1.82.5"
ffsend-api = "0.7.3"
serde_json = "1.0.114"
chrono = "0.4.35"
image = { version = "0.25.0", features = ["rayon"] }
ipp = "5.0.3"
nokhwa = { git = "https://github.com/l1npengtul/nokhwa", branch="0.10", features = ["input-native", "output-threaded"] }
zune-jpeg = "0.4.11"
jpeg-encoder = "0.6.0"
static_init = "1.0.3"
lazy_static = "1.4.0"
dlopen = "0.1.8"
noise = "0.8.2"
dashmap = "5.5.3"
turborand = "0.10.1"
pathsep = "0.1.1"
tokio = { version = "1.36.0", features = ["rt-multi-thread"] }
gphoto2 = "3.2.3"
ahash = "0.8.10"
img-parts = "0.3.0"
little_exif = "0.3.1"
url = "2.5.0"
num = "0.4.1"
num-traits = "0.2.18"
num-derive = "0.4.2"
nom-exif = "1.2.0"

[profile.dev]
opt-level = 3
