[package]
name = "momento_booth_native_helpers"
version = "0.1.0"
edition = "2021"

[lib]
name = "momento_booth_native_helpers"
crate-type = ["lib", "staticlib", "cdylib"]

[dependencies]
anyhow = "1.0.75"
derive_more = "0.99.17"
atom_table = "1.1.0"
flutter_rust_bridge = "=1.82.3"
ffsend-api = "0.7.3"
serde_json = "1.0.107"
chrono = "0.4.31"
image = "0.24.7"
nokhwa = { git = "https://github.com/l1npengtul/nokhwa", branch="0.10", features = ["input-native", "output-threaded"] }
zune-jpeg = "0.3.17"
jpeg-encoder = "0.6.0"
static_init = "1.0.3"
lazy_static = "1.4.0"
dlopen = "0.1.8"
noise = "0.8.2"
dashmap = "5.5.3"
turborand = "0.10.0"
pathsep = "0.1.1"
tokio = "1.32.0"
gphoto2 = "3.2.3"
ahash = "0.8.4"

[profile.dev]
opt-level = 3
