[package]
name = "rust_lib_momento_booth"
version = "0.2.0"
edition = "2021"
rust-version = "1.80"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = { version = "=2.5.0", features = ["chrono"] }
anyhow = "1.0.89"
atom_table = "1.1.0"
ffsend-api = "0.7.3"
serde_json = "1.0.128"
chrono = "0.4.38"
image = { version = "0.25.2", features = ["rayon"] }
ipp = "5.0.4"
zune-jpeg = "0.4.13"
jpeg-encoder = "0.6.0"
dlopen = "0.1.8"
noise = "0.9.0"
dashmap = "6.1.0"
turborand = "0.10.1"
pathsep = "0.1.1"
tokio = { version = "1.40.0", features = ["rt-multi-thread"] }
gphoto2 = "3.3.1"
ahash = "0.8.11"
img-parts = "0.3.0"
little_exif = "0.5.0"
url = "2.5.2"
num = "0.4.3"
num-traits = "0.2.19"
num-derive = "0.4.2"
rexiv2 = { version = "0.10.0", features = ["raw-tag-access"] }
gexiv2-sys = "1.4.0"
regex = "1.11.0"
log = "0.4.22"
flutter_logger = "0.6.1"
nokhwa = { version = "0.10.4", features = ["input-native", "output-threaded", "flume"], git = "https://github.com/kendfrey/nokhwa.git", branch = "0.10" }
rustc_version_runtime = "0.3.0"
libc = "0.2.159"

[build-dependencies]
bindgen = "0.70.1"
pkg-config = "0.3.31"

[profile.dev]
opt-level = 3
