name: PR CI Documentation

env:
  MDBOOK_VERSION: "0.4.34"
  BOOK_LOCATION: "documentation"

on:
  pull_request:
    branches: [ main ]
    paths: [ documentation/**, .github/workflows/pr-ci-documentation.yml, README.md ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: ${{ env.MDBOOK_VERSION }}

      - name: Install minimal Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Setup sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3

      - name: Install mermaid preprocessor for mdBook
        uses: baptiste0928/cargo-install@v3
        with:
          crate: mdbook-mermaid

      - name: Install admonish preprocessor for mdBook
        uses: baptiste0928/cargo-install@v3
        with:
          crate: mdbook-admonish

      - name: Build static site
        run: mdbook build ${{ env.BOOK_LOCATION }} --dest-dir ../_site
